### ISSUE TITLE
History Page highlights

### ISSUE THREAD

**Issue by ondreian** [ondreian/skillbuilder#2]
On the history screen cells whose value has changed from cycle to cycle should be highlighted in yellow. Code already exists that adds a class to these cells, I just need a CSS rule that changes the background color. Here's the rule:

```css
td.myhilite {
    background-color: yellow;
}
```
